clone:
    hg:
        image: plugins/hg

pipeline:
    npm:
        image: node
        commands:
            - sh .bower_allow_root.sh
            - npm -s install --unsafe-perm
            - npm test
        volumes:
            - cache-npm:/root/.npm
